[tool.poetry]
name = "wideboi"
version = "0.1.0"
description = ""
authors = ["Rahul Sengottuvelu <rgs@ramp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
modal = "^0.55.4022"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
